name: couldai_user_app
description: "A password management app built with Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  provider: ^6.1.1
  encrypt: ^5.0.1
  crypto: ^3.0.3

flutter:
  uses-material-design: true